### ISSUE TITLE
What are those components 

### ISSUE THREAD

**Issue by danielo515** [FiberJW/stature#2]
Hello,
I just noticed on your readme that you are using some react components on your example (Text and Button). What are those components? Are related to your library on any way? If not I think you better use normal html tags to avoid distractions. 

Regards

**Comment by FiberJW** [comment]
They're from BsReactNative: https://github.com/FiberJW/stature/commit/36b24b10a969ba035fdd3c97220947a36b2fa3b0#diff-04c6e90faac2675aa89e2176d2eec7d8R14

**Comment by danielo515** [comment]
Oh! thanks
